# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Gregor Riegler
email:            rieglerg85@gmail.com
twitter_username: gregor_riegler
github_username:  gregorriegler
tagline:          'merciless refactorer'
description:      'merciless refactorer'
url:              http://gregorriegler.com
#baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Gregor Riegler'
  url:            http://gregorriegler.com

pagination:
  enabled: true
  debug: false
  per_page: 5
  permalink: "/blog/page:num/"

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-twitter-plugin

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

# Sidebar link settings
sidebar_home_link:  false
sidebar_blog_link:  false   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

disqus:
  shortname:  gregorriegler

#google_analytics: UA-100461102-1